module.exports = {
  extEnable: true,
  extAppid: process.env.APP_ID,
  directCommit: false,
  ext: {
    BASE_URL : process.env.BASE_URL,
    ORG_ID : null,
    APP_ID : process.env.APP_ID,
    APP_NAME : '智富小店',
    HS_DOMAIN: '666666.finogeeks.com',
    APP_DESCRIPTION : '科技让投资更轻松',
    CATEGORY: 'stock',
    LOGIN_TYPE: 'unionid',
    THEME_COLOR : {
      NAV_bg : '#ed3e26',
      TP_n : '#ed3e26',
      TP_p : '#BD311E',
      TP_d : '#F7B1A8',
      Btn_n : '#ed3e26',
      Btn_p : '#BD311E',
      Btn_d : '#F7B1A8',
      Bubble_Host_fill : '#FFF3F1',
      Bubble_Host_border : '#FFD4CE',
      Bubble_Guest_fill : '#FFFFFF',
      Bubble_Guest_border : '#CFCFCF',
    },
    CUSTOM_CONFIG : {
      DISPATCH_TIMEOUT_REDIRECT : 'smart-bot',
      LEAVE_MESSAGE_SELECT_LOCATION : false,
      FEATURE_FORCE_CONSULTING_WITH_PHONE : false,
      FEATURE_TWEET_TIP_TYPE: 'DISCLAIMER',
      FEATURE_FORWARD_PRODUCT_DETAIL: true,
      FEATURE_COMMENT_WITH_FUND_ACCOUNT:'true', 
      FUND_ACCOUNT_LOGIN_URL:'https://wxnewtest.fcsc.com/fcscoauth/oauth/authorize?client_id=IF08-06411&redirect_uri=https://swan.finogeeks.club/webapps/pages/authorize&response_type=token&scope=api_info',
    },
  },
};
